ministryofjustice/laa-court-data-api

.circleci/config.yml
.github/CODEOWNERS
.gitignore
helm_deploy/laa-court-data-api/values-dev.yaml
helm_deploy/laa-court-data-api/values-prod.yaml
helm_deploy/laa-court-data-api/values-staging.yaml
helm_deploy/laa-court-data-api/values-uat.yaml

Adding in the initial CircleCI config to allow for linting and preparing for the project to contain code. 
- [AAC-268](https://dsdmoj.atlassian.net/browse/AAC-268)

AAC-268 - Add initial CircleCI config

---

.circleci/config.yml
Pipfile
Pipfile.lock
README.md

Update the pipfile to use dev dependencies to reduce image size.
- [AAC-439](https://dsdmoj.atlassian.net/browse/AAC-439)

AAC-439 - Update to use dev dependencies to reduce size

---

helm_deploy/laa-court-data-api/values-dev.yaml
helm_deploy/laa-court-data-api/values-prod.yaml
helm_deploy/laa-court-data-api/values-staging.yaml
helm_deploy/laa-court-data-api/values-uat.yaml

Add Basic Auth to ingress as described in [this](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/helloworld-app-deploy.html#add-http-basic-authentication) documentation
- [AAC-441](https://dsdmoj.atlassian.net/browse/AAC-441)

AAC-441 - Add basic auth annotation

---

.circleci/config.yml
helm_deploy/laa-court-data-api/values-staging.yaml
helm_deploy/laa-court-data-api/values-uat.yaml
laa_court_data_api_app/models/hearing/hearing_result.py
postman/environments/staging.postman_environment.json
postman/environments/uat.postman_environment.json

Update pipelines to deploy to staging and uat
- [AAC-557](https://dsdmoj.atlassian.net/browse/AAC-557)

AAC-557 - Update pipeline for UAT and Staging

---

laa_court_data_api_app/models/defendants/defendant_summary.py
laa_court_data_api_app/models/defendants/defendants_response.py
laa_court_data_api_app/models/defendants/delegated_powers.py
laa_court_data_api_app/models/defendants/laa_application.py
laa_court_data_api_app/models/defendants/offence_summary.py
laa_court_data_api_app/models/defendants/plea.py
laa_court_data_api_app/models/defendants/representation_order.py
laa_court_data_api_app/models/defendants/verdict.py
laa_court_data_api_app/models/defendants/verdict_type.py
laa_court_data_api_app/routers/defendants.py

Our initial implementation of the defendants mapping left us missing some fields that are needed for the integration on the front end. This PR addresses those missing fields.
- [AAC-573](https://dsdmoj.atlassian.net/browse/AAC-573)

AAC-573 - Fix defendant mapping

---

laa_court_data_api_app/routers/laa_references.py

add `f` to beginning of log so it is formatted correctly
N/A

log not using correct format

---

helm_deploy/laa-court-data-api/values-dev.yaml
helm_deploy/laa-court-data-api/values-prod.yaml
helm_deploy/laa-court-data-api/values-staging.yaml
helm_deploy/laa-court-data-api/values-uat.yaml
helm_deploy/laa-court-data-api/values.yaml
postman/environments/dev.postman_environment.json
postman/environments/production.postman_environment.json
postman/environments/staging.postman_environment.json
postman/environments/uat.postman_environment.json

Update the ingresses to use the new domain we have and certificates created. 
- [AAC-581](https://dsdmoj.atlassian.net/browse/AAC-581)

AAC-581 - Update Ingresses to use domain

---

helm_deploy/laa-court-data-api/values-dev.yaml
helm_deploy/laa-court-data-api/values-prod.yaml
helm_deploy/laa-court-data-api/values-staging.yaml
helm_deploy/laa-court-data-api/values-uat.yaml
helm_deploy/laa-court-data-api/values.yaml
laa_court_data_api_app/models/hearing/external/hearing.py
laa_court_data_api_app/models/hearing/internal/hearing.py
laa_court_data_api_app/routers/laa_references.py
test/routers/laa_references/patch_test.py

Hearings model was slightly wrong so Crime apps made a fix and this adjusts the models to that fix. Validation was also added to the Patch request for security.
- [AAC-569](https://dsdmoj.atlassian.net/browse/AAC-569)

AAC-569 - Fix Hearings Model

---

laa_court_data_api_app/models/hearing_summaries/defendants.py
laa_court_data_api_app/models/hearing_summaries/hearing_summary.py
laa_court_data_api_app/models/prosecution_cases/hearing_summary.py
laa_court_data_api_app/routers/hearing_summaries.py

Add a slim defendants object to the hearing summary instead of the GUID that is presented currently. 
- [AAC-570](https://dsdmoj.atlassian.net/browse/AAC-570)

AAC-570 - Update hearing summaries

---

.circleci/config.yml

Add the ability to push our application to production
- [AAC-609](https://dsdmoj.atlassian.net/browse/AAC-609)

AAC-609 - Add production pipeline push

---

laa_court_data_api_app/models/hearing_summaries/hearing_summaries_response.py
laa_court_data_api_app/routers/hearing_summaries.py

Add overall defendants so summary page can show all defendants then specific defendants per day.
- [AAC-610](https://dsdmoj.atlassian.net/browse/AAC-610)

AAC-610 - Add overall defendants

---

Pipfile
Pipfile.lock
laa_court_data_api_app/config/logging_config.py
laa_court_data_api_app/internal/court_data_adaptor_client.py
laa_court_data_api_app/internal/oauth_client.py
laa_court_data_api_app/main.py
laa_court_data_api_app/routers/defendants.py
laa_court_data_api_app/routers/hearing.py
laa_court_data_api_app/routers/hearing_events.py
laa_court_data_api_app/routers/hearing_summaries.py
laa_court_data_api_app/routers/laa_references.py
laa_court_data_api_app/routers/ping.py

Move to using structured logging for better searching when in Kibana
- [AAC-591](https://dsdmoj.atlassian.net/browse/AAC-591)

AAC-591 - Add Struct log

---

laa_court_data_api_app/routers/hearing.py
postman/collections/hearing.postman_collection.json
test/routers/fixtures.py
test/routers/hearing_test.py

Add hearing date from query param to CDA call for hearings
- [AAC-424](https://dsdmoj.atlassian.net/browse/AAC-424)

AAC-424 - Add hearing date to hearings call

---

laa_court_data_api_app/routers/defendants.py

Adds a name builder method so we no longer get NONE where a name is not provided
- [AAC-634](https://dsdmoj.atlassian.net/browse/AAC-634)

AAC-634 - Add name builder method

---

laa_court_data_api_app/constants/endpoint_constants.py
laa_court_data_api_app/routers/defendants.py
laa_court_data_api_app/routers/hearing.py
laa_court_data_api_app/routers/hearing_summaries.py
laa_court_data_api_app/routers/laa_references.py
test/routers/fixtures.py
test/routers/laa_references/patch_test.py

Move endpoints to a constants file
- [AAC-655](https://dsdmoj.atlassian.net/browse/AAC-655)

Move endpoints to constant file

---

laa_court_data_api_app/routers/hearing_summaries.py
laa_court_data_api_app/routers/laa_references.py

Based on the last 2 codesmells ive made the following changes:
- Add parameter to lambda to ensure the param doesnt change
- Use more efficient regex to prevent backtracking
- [AAC-685](https://dsdmoj.atlassian.net/browse/AAC-685)

AAC-685 - Update code based on SQ Codesmells

---

Pipfile
Pipfile.lock
laa_court_data_api_app/internal/court_data_adaptor_client.py
laa_court_data_api_app/internal/oauth_client.py

Add circuit breaker pattern around our http calls to try and ensure that there are no issues when it comes to downtime on the end services. 
- [AAC-687](https://dsdmoj.atlassian.net/browse/AAC-687)

AAC-687 - Add circuit breaker around http calls

---

laa_court_data_api_app/internal/court_data_adaptor_client.py

Increase timeout from 5 to 15 seconds to try and accomodate for common platform slow downs
- [AAC-699](https://dsdmoj.atlassian.net/browse/AAC-699)

AAC-699 - Fix timeout

---

laa_court_data_api_app/models/case_summaries/defence_counsel.py
laa_court_data_api_app/models/prosecution_cases/defence_counsel.py

Update attendance_day array to use str instead of datetime due to parsing issues
- [AAC-747](https://dsdmoj.atlassian.net/browse/AAC-747)

AAC-747 - Update defence counsel to use str

---

laa_court_data_api_app/internal/court_data_adaptor_client.py

- Update the Laa-Correlation-Id header to be X-Request-Id as per new change in CDA
- [AAC-](link to jira ticket)
https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(_source),filters:!(),index:'167701b0-f8c0-11ec-b95c-1d65c3682287',interval:auto,query:(language:kuery,query:cf25e15c127e47fea34b1203543b33c7),sort:!())

Change laa-transaction-id to request-id

---

.github/dependabot.yml

- Add Gitactions to dependabot
N/A

Add Gitactions to dependabot

---

Pipfile
Pipfile.lock

Update all dependabot python dependencies (date: 18/04/2023)
- [CTSKF-346](https://dsdmoj.atlassian.net/jira/software/c/projects/CTSKF/boards/987?modal=detail&selectedIssue=CTSKF-346)
[CTSKF-346]: https://dsdmoj.atlassian.net/browse/CTSKF-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update pipfile and lockfile

---

helm_deploy/laa-court-data-api/templates/deployment.yaml

Pull secrets from a new AWS-controlled secret

ACD-667: Switch to AWS secret manager
